### ISSUE TITLE
Unable to change name and font color using setter functions

### ISSUE THREAD

**Issue by psbj** [asl97/ch.py-abandon#5]
The setNameColor and setFontColor functions do not work in commits b6acba1 and 9d23426 (haven't tried anything earlier than those).

Changing the default colors in the library itself works, but using the functions seems to do nothing.

I've looked myself but I'm at a loss as to what's wrong.

These functions do work in Nullspeaker's ch.py, perhaps looking back can help.

I hope this can be fixed soon as it seems to be the most promising, active, and stable of the chatango libraries out there.

Thank you.

**Comment by asl97** [comment]
broken by the new user class: https://github.com/asl97/ch.py/commit/10cfd0aaa8822a7446277cb4090239264c8e414a
fixed in https://github.com/asl97/ch.py/commit/7b31aa4eca1fc7fd4a0f36f32595895675d0b026
